# Site settings
title: Kalpana Poosarla
header-img: img/home-bg.png
email: joyci09@gmail.com
copyright_name: Kalpana01
description: > # this means to ignore newlines until "baseurl:"
  “How you look at it is pretty much how you'll see it” 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kalpana01
learn_profile: Kalpana01
email_username: joyci09@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
